name: Publish to GitHub Packages

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  publish-to-github-packages:
    uses: quidli/github-actions/.github/workflows/publish-artifact.yml@main
    secrets:
      username: ${{ secrets.QUIDLI_PACKAGES_USERNAME }}
      password: ${{ secrets.QUIDLI_PACKAGES_TOKEN }}